export const CATEGORIES_ACTION_TYPES = {
  SET_CATEGORIES_MAP: 'category/SET_CATEGORIES_MAP',
};

export const CART_ACTION_TYPES = {
  TOGGLE_CART_OPEN: 'TOGGLE_CART_OPEN',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_CART_COUNT: 'SET_CART_COUNT',
  SET_CART_TOTAL: 'SET_CART_TOTAL',
};
